template1:
  name: RUP Template
  attributes:
    atribuete1:
      name: Scope
      input_type: input
      data_type: string
      data_input:
    atribuete2:
      name: Primary Actor
      input_type: text_field_tag
      data_type: string
      data_input:
    atribuete3:
      name: Basic Flow
      input_type: text_area_tag
      data_type: text
      data_input:
    atribuete4:
      name: Alternate Flow 1
      input_type: text_area_tag
      data_type: text
      data_input:
    atribuete5:
      name: Alternate Flow 2
      input_type: text_area_tag
      data_type: text
      data_input:
    atribuete6:
      name: Alternate Flow 3
      input_type: text_area_tag
      data_type: text
      data_input: