require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DocumentProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # DocumentProject. As you add validations to DocumentProject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DocumentProjectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all document_projects as @document_projects" do
      document_project = DocumentProject.create! valid_attributes
      get :index, {}, valid_session
      assigns(:document_projects).should eq([document_project])
    end
  end

  describe "GET show" do
    it "assigns the requested document_project as @document_project" do
      document_project = DocumentProject.create! valid_attributes
      get :show, {:id => document_project.to_param}, valid_session
      assigns(:document_project).should eq(document_project)
    end
  end

  describe "GET new" do
    it "assigns a new document_project as @document_project" do
      get :new, {}, valid_session
      assigns(:document_project).should be_a_new(DocumentProject)
    end
  end

  describe "GET edit" do
    it "assigns the requested document_project as @document_project" do
      document_project = DocumentProject.create! valid_attributes
      get :edit, {:id => document_project.to_param}, valid_session
      assigns(:document_project).should eq(document_project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DocumentProject" do
        expect {
          post :create, {:document_project => valid_attributes}, valid_session
        }.to change(DocumentProject, :count).by(1)
      end

      it "assigns a newly created document_project as @document_project" do
        post :create, {:document_project => valid_attributes}, valid_session
        assigns(:document_project).should be_a(DocumentProject)
        assigns(:document_project).should be_persisted
      end

      it "redirects to the created document_project" do
        post :create, {:document_project => valid_attributes}, valid_session
        response.should redirect_to(DocumentProject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved document_project as @document_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentProject.any_instance.stub(:save).and_return(false)
        post :create, {:document_project => { "name" => "invalid value" }}, valid_session
        assigns(:document_project).should be_a_new(DocumentProject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentProject.any_instance.stub(:save).and_return(false)
        post :create, {:document_project => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested document_project" do
        document_project = DocumentProject.create! valid_attributes
        # Assuming there are no other document_projects in the database, this
        # specifies that the DocumentProject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DocumentProject.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => document_project.to_param, :document_project => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested document_project as @document_project" do
        document_project = DocumentProject.create! valid_attributes
        put :update, {:id => document_project.to_param, :document_project => valid_attributes}, valid_session
        assigns(:document_project).should eq(document_project)
      end

      it "redirects to the document_project" do
        document_project = DocumentProject.create! valid_attributes
        put :update, {:id => document_project.to_param, :document_project => valid_attributes}, valid_session
        response.should redirect_to(document_project)
      end
    end

    describe "with invalid params" do
      it "assigns the document_project as @document_project" do
        document_project = DocumentProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentProject.any_instance.stub(:save).and_return(false)
        put :update, {:id => document_project.to_param, :document_project => { "name" => "invalid value" }}, valid_session
        assigns(:document_project).should eq(document_project)
      end

      it "re-renders the 'edit' template" do
        document_project = DocumentProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentProject.any_instance.stub(:save).and_return(false)
        put :update, {:id => document_project.to_param, :document_project => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested document_project" do
      document_project = DocumentProject.create! valid_attributes
      expect {
        delete :destroy, {:id => document_project.to_param}, valid_session
      }.to change(DocumentProject, :count).by(-1)
    end

    it "redirects to the document_projects list" do
      document_project = DocumentProject.create! valid_attributes
      delete :destroy, {:id => document_project.to_param}, valid_session
      response.should redirect_to(document_projects_url)
    end
  end

end
