require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DocumentUseCasesController do

  # This should return the minimal set of attributes required to create a valid
  # DocumentUseCase. As you add validations to DocumentUseCase, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all document_use_cases as @document_use_cases" do
      document_use_case = DocumentUseCase.create! valid_attributes
      get :index
      assigns(:document_use_cases).should eq([document_use_case])
    end
  end

  describe "GET show" do
    it "assigns the requested document_use_case as @document_use_case" do
      document_use_case = DocumentUseCase.create! valid_attributes
      get :show, :id => document_use_case.id.to_s
      assigns(:document_use_case).should eq(document_use_case)
    end
  end

  describe "GET new" do
    it "assigns a new document_use_case as @document_use_case" do
      get :new
      assigns(:document_use_case).should be_a_new(DocumentUseCase)
    end
  end

  describe "GET edit" do
    it "assigns the requested document_use_case as @document_use_case" do
      document_use_case = DocumentUseCase.create! valid_attributes
      get :edit, :id => document_use_case.id.to_s
      assigns(:document_use_case).should eq(document_use_case)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DocumentUseCase" do
        expect {
          post :create, :document_use_case => valid_attributes
        }.to change(DocumentUseCase, :count).by(1)
      end

      it "assigns a newly created document_use_case as @document_use_case" do
        post :create, :document_use_case => valid_attributes
        assigns(:document_use_case).should be_a(DocumentUseCase)
        assigns(:document_use_case).should be_persisted
      end

      it "redirects to the created document_use_case" do
        post :create, :document_use_case => valid_attributes
        response.should redirect_to(DocumentUseCase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved document_use_case as @document_use_case" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentUseCase.any_instance.stub(:save).and_return(false)
        post :create, :document_use_case => {}
        assigns(:document_use_case).should be_a_new(DocumentUseCase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentUseCase.any_instance.stub(:save).and_return(false)
        post :create, :document_use_case => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested document_use_case" do
        document_use_case = DocumentUseCase.create! valid_attributes
        # Assuming there are no other document_use_cases in the database, this
        # specifies that the DocumentUseCase created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DocumentUseCase.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => document_use_case.id, :document_use_case => {'these' => 'params'}
      end

      it "assigns the requested document_use_case as @document_use_case" do
        document_use_case = DocumentUseCase.create! valid_attributes
        put :update, :id => document_use_case.id, :document_use_case => valid_attributes
        assigns(:document_use_case).should eq(document_use_case)
      end

      it "redirects to the document_use_case" do
        document_use_case = DocumentUseCase.create! valid_attributes
        put :update, :id => document_use_case.id, :document_use_case => valid_attributes
        response.should redirect_to(document_use_case)
      end
    end

    describe "with invalid params" do
      it "assigns the document_use_case as @document_use_case" do
        document_use_case = DocumentUseCase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentUseCase.any_instance.stub(:save).and_return(false)
        put :update, :id => document_use_case.id.to_s, :document_use_case => {}
        assigns(:document_use_case).should eq(document_use_case)
      end

      it "re-renders the 'edit' template" do
        document_use_case = DocumentUseCase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentUseCase.any_instance.stub(:save).and_return(false)
        put :update, :id => document_use_case.id.to_s, :document_use_case => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested document_use_case" do
      document_use_case = DocumentUseCase.create! valid_attributes
      expect {
        delete :destroy, :id => document_use_case.id.to_s
      }.to change(DocumentUseCase, :count).by(-1)
    end

    it "redirects to the document_use_cases list" do
      document_use_case = DocumentUseCase.create! valid_attributes
      delete :destroy, :id => document_use_case.id.to_s
      response.should redirect_to(document_use_cases_url)
    end
  end

end
