require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectRoleUsersController do

  # This should return the minimal set of attributes required to create a valid
  # ProjectRoleUser. As you add validations to ProjectRoleUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectRoleUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all project_role_users as @project_role_users" do
      project_role_user = ProjectRoleUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:project_role_users).should eq([project_role_user])
    end
  end

  describe "GET show" do
    it "assigns the requested project_role_user as @project_role_user" do
      project_role_user = ProjectRoleUser.create! valid_attributes
      get :show, {:id => project_role_user.to_param}, valid_session
      assigns(:project_role_user).should eq(project_role_user)
    end
  end

  describe "GET new" do
    it "assigns a new project_role_user as @project_role_user" do
      get :new, {}, valid_session
      assigns(:project_role_user).should be_a_new(ProjectRoleUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_role_user as @project_role_user" do
      project_role_user = ProjectRoleUser.create! valid_attributes
      get :edit, {:id => project_role_user.to_param}, valid_session
      assigns(:project_role_user).should eq(project_role_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectRoleUser" do
        expect {
          post :create, {:project_role_user => valid_attributes}, valid_session
        }.to change(ProjectRoleUser, :count).by(1)
      end

      it "assigns a newly created project_role_user as @project_role_user" do
        post :create, {:project_role_user => valid_attributes}, valid_session
        assigns(:project_role_user).should be_a(ProjectRoleUser)
        assigns(:project_role_user).should be_persisted
      end

      it "redirects to the created project_role_user" do
        post :create, {:project_role_user => valid_attributes}, valid_session
        response.should redirect_to(ProjectRoleUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_role_user as @project_role_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectRoleUser.any_instance.stub(:save).and_return(false)
        post :create, {:project_role_user => {  }}, valid_session
        assigns(:project_role_user).should be_a_new(ProjectRoleUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectRoleUser.any_instance.stub(:save).and_return(false)
        post :create, {:project_role_user => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_role_user" do
        project_role_user = ProjectRoleUser.create! valid_attributes
        # Assuming there are no other project_role_users in the database, this
        # specifies that the ProjectRoleUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProjectRoleUser.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => project_role_user.to_param, :project_role_user => { "these" => "params" }}, valid_session
      end

      it "assigns the requested project_role_user as @project_role_user" do
        project_role_user = ProjectRoleUser.create! valid_attributes
        put :update, {:id => project_role_user.to_param, :project_role_user => valid_attributes}, valid_session
        assigns(:project_role_user).should eq(project_role_user)
      end

      it "redirects to the project_role_user" do
        project_role_user = ProjectRoleUser.create! valid_attributes
        put :update, {:id => project_role_user.to_param, :project_role_user => valid_attributes}, valid_session
        response.should redirect_to(project_role_user)
      end
    end

    describe "with invalid params" do
      it "assigns the project_role_user as @project_role_user" do
        project_role_user = ProjectRoleUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectRoleUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => project_role_user.to_param, :project_role_user => {  }}, valid_session
        assigns(:project_role_user).should eq(project_role_user)
      end

      it "re-renders the 'edit' template" do
        project_role_user = ProjectRoleUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectRoleUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => project_role_user.to_param, :project_role_user => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_role_user" do
      project_role_user = ProjectRoleUser.create! valid_attributes
      expect {
        delete :destroy, {:id => project_role_user.to_param}, valid_session
      }.to change(ProjectRoleUser, :count).by(-1)
    end

    it "redirects to the project_role_users list" do
      project_role_user = ProjectRoleUser.create! valid_attributes
      delete :destroy, {:id => project_role_user.to_param}, valid_session
      response.should redirect_to(project_role_users_url)
    end
  end

end
