require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaskUsersController do

  # This should return the minimal set of attributes required to create a valid
  # TaskUser. As you add validations to TaskUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "task_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaskUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all task_users as @task_users" do
      task_user = TaskUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:task_users).should eq([task_user])
    end
  end

  describe "GET show" do
    it "assigns the requested task_user as @task_user" do
      task_user = TaskUser.create! valid_attributes
      get :show, {:id => task_user.to_param}, valid_session
      assigns(:task_user).should eq(task_user)
    end
  end

  describe "GET new" do
    it "assigns a new task_user as @task_user" do
      get :new, {}, valid_session
      assigns(:task_user).should be_a_new(TaskUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested task_user as @task_user" do
      task_user = TaskUser.create! valid_attributes
      get :edit, {:id => task_user.to_param}, valid_session
      assigns(:task_user).should eq(task_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaskUser" do
        expect {
          post :create, {:task_user => valid_attributes}, valid_session
        }.to change(TaskUser, :count).by(1)
      end

      it "assigns a newly created task_user as @task_user" do
        post :create, {:task_user => valid_attributes}, valid_session
        assigns(:task_user).should be_a(TaskUser)
        assigns(:task_user).should be_persisted
      end

      it "redirects to the created task_user" do
        post :create, {:task_user => valid_attributes}, valid_session
        response.should redirect_to(TaskUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved task_user as @task_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaskUser.any_instance.stub(:save).and_return(false)
        post :create, {:task_user => { "task_id" => "invalid value" }}, valid_session
        assigns(:task_user).should be_a_new(TaskUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaskUser.any_instance.stub(:save).and_return(false)
        post :create, {:task_user => { "task_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested task_user" do
        task_user = TaskUser.create! valid_attributes
        # Assuming there are no other task_users in the database, this
        # specifies that the TaskUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TaskUser.any_instance.should_receive(:update_attributes).with({ "task_id" => "1" })
        put :update, {:id => task_user.to_param, :task_user => { "task_id" => "1" }}, valid_session
      end

      it "assigns the requested task_user as @task_user" do
        task_user = TaskUser.create! valid_attributes
        put :update, {:id => task_user.to_param, :task_user => valid_attributes}, valid_session
        assigns(:task_user).should eq(task_user)
      end

      it "redirects to the task_user" do
        task_user = TaskUser.create! valid_attributes
        put :update, {:id => task_user.to_param, :task_user => valid_attributes}, valid_session
        response.should redirect_to(task_user)
      end
    end

    describe "with invalid params" do
      it "assigns the task_user as @task_user" do
        task_user = TaskUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaskUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => task_user.to_param, :task_user => { "task_id" => "invalid value" }}, valid_session
        assigns(:task_user).should eq(task_user)
      end

      it "re-renders the 'edit' template" do
        task_user = TaskUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaskUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => task_user.to_param, :task_user => { "task_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested task_user" do
      task_user = TaskUser.create! valid_attributes
      expect {
        delete :destroy, {:id => task_user.to_param}, valid_session
      }.to change(TaskUser, :count).by(-1)
    end

    it "redirects to the task_users list" do
      task_user = TaskUser.create! valid_attributes
      delete :destroy, {:id => task_user.to_param}, valid_session
      response.should redirect_to(task_users_url)
    end
  end

end
