require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UseCaseGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # UseCaseGroup. As you add validations to UseCaseGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UseCaseGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all use_case_groups as @use_case_groups" do
      use_case_group = UseCaseGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:use_case_groups).should eq([use_case_group])
    end
  end

  describe "GET show" do
    it "assigns the requested use_case_group as @use_case_group" do
      use_case_group = UseCaseGroup.create! valid_attributes
      get :show, {:id => use_case_group.to_param}, valid_session
      assigns(:use_case_group).should eq(use_case_group)
    end
  end

  describe "GET new" do
    it "assigns a new use_case_group as @use_case_group" do
      get :new, {}, valid_session
      assigns(:use_case_group).should be_a_new(UseCaseGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested use_case_group as @use_case_group" do
      use_case_group = UseCaseGroup.create! valid_attributes
      get :edit, {:id => use_case_group.to_param}, valid_session
      assigns(:use_case_group).should eq(use_case_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UseCaseGroup" do
        expect {
          post :create, {:use_case_group => valid_attributes}, valid_session
        }.to change(UseCaseGroup, :count).by(1)
      end

      it "assigns a newly created use_case_group as @use_case_group" do
        post :create, {:use_case_group => valid_attributes}, valid_session
        assigns(:use_case_group).should be_a(UseCaseGroup)
        assigns(:use_case_group).should be_persisted
      end

      it "redirects to the created use_case_group" do
        post :create, {:use_case_group => valid_attributes}, valid_session
        response.should redirect_to(UseCaseGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved use_case_group as @use_case_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        UseCaseGroup.any_instance.stub(:save).and_return(false)
        post :create, {:use_case_group => { "name" => "invalid value" }}, valid_session
        assigns(:use_case_group).should be_a_new(UseCaseGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UseCaseGroup.any_instance.stub(:save).and_return(false)
        post :create, {:use_case_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested use_case_group" do
        use_case_group = UseCaseGroup.create! valid_attributes
        # Assuming there are no other use_case_groups in the database, this
        # specifies that the UseCaseGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UseCaseGroup.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => use_case_group.to_param, :use_case_group => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested use_case_group as @use_case_group" do
        use_case_group = UseCaseGroup.create! valid_attributes
        put :update, {:id => use_case_group.to_param, :use_case_group => valid_attributes}, valid_session
        assigns(:use_case_group).should eq(use_case_group)
      end

      it "redirects to the use_case_group" do
        use_case_group = UseCaseGroup.create! valid_attributes
        put :update, {:id => use_case_group.to_param, :use_case_group => valid_attributes}, valid_session
        response.should redirect_to(use_case_group)
      end
    end

    describe "with invalid params" do
      it "assigns the use_case_group as @use_case_group" do
        use_case_group = UseCaseGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UseCaseGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => use_case_group.to_param, :use_case_group => { "name" => "invalid value" }}, valid_session
        assigns(:use_case_group).should eq(use_case_group)
      end

      it "re-renders the 'edit' template" do
        use_case_group = UseCaseGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UseCaseGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => use_case_group.to_param, :use_case_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested use_case_group" do
      use_case_group = UseCaseGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => use_case_group.to_param}, valid_session
      }.to change(UseCaseGroup, :count).by(-1)
    end

    it "redirects to the use_case_groups list" do
      use_case_group = UseCaseGroup.create! valid_attributes
      delete :destroy, {:id => use_case_group.to_param}, valid_session
      response.should redirect_to(use_case_groups_url)
    end
  end

end
