require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequirementTemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # RequirementTemplate. As you add validations to RequirementTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequirementTemplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all requirement_templates as @requirement_templates" do
      requirement_template = RequirementTemplate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:requirement_templates).should eq([requirement_template])
    end
  end

  describe "GET show" do
    it "assigns the requested requirement_template as @requirement_template" do
      requirement_template = RequirementTemplate.create! valid_attributes
      get :show, {:id => requirement_template.to_param}, valid_session
      assigns(:requirement_template).should eq(requirement_template)
    end
  end

  describe "GET new" do
    it "assigns a new requirement_template as @requirement_template" do
      get :new, {}, valid_session
      assigns(:requirement_template).should be_a_new(RequirementTemplate)
    end
  end

  describe "GET edit" do
    it "assigns the requested requirement_template as @requirement_template" do
      requirement_template = RequirementTemplate.create! valid_attributes
      get :edit, {:id => requirement_template.to_param}, valid_session
      assigns(:requirement_template).should eq(requirement_template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RequirementTemplate" do
        expect {
          post :create, {:requirement_template => valid_attributes}, valid_session
        }.to change(RequirementTemplate, :count).by(1)
      end

      it "assigns a newly created requirement_template as @requirement_template" do
        post :create, {:requirement_template => valid_attributes}, valid_session
        assigns(:requirement_template).should be_a(RequirementTemplate)
        assigns(:requirement_template).should be_persisted
      end

      it "redirects to the created requirement_template" do
        post :create, {:requirement_template => valid_attributes}, valid_session
        response.should redirect_to(RequirementTemplate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved requirement_template as @requirement_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequirementTemplate.any_instance.stub(:save).and_return(false)
        post :create, {:requirement_template => { "name" => "invalid value" }}, valid_session
        assigns(:requirement_template).should be_a_new(RequirementTemplate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequirementTemplate.any_instance.stub(:save).and_return(false)
        post :create, {:requirement_template => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested requirement_template" do
        requirement_template = RequirementTemplate.create! valid_attributes
        # Assuming there are no other requirement_templates in the database, this
        # specifies that the RequirementTemplate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RequirementTemplate.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => requirement_template.to_param, :requirement_template => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested requirement_template as @requirement_template" do
        requirement_template = RequirementTemplate.create! valid_attributes
        put :update, {:id => requirement_template.to_param, :requirement_template => valid_attributes}, valid_session
        assigns(:requirement_template).should eq(requirement_template)
      end

      it "redirects to the requirement_template" do
        requirement_template = RequirementTemplate.create! valid_attributes
        put :update, {:id => requirement_template.to_param, :requirement_template => valid_attributes}, valid_session
        response.should redirect_to(requirement_template)
      end
    end

    describe "with invalid params" do
      it "assigns the requirement_template as @requirement_template" do
        requirement_template = RequirementTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequirementTemplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => requirement_template.to_param, :requirement_template => { "name" => "invalid value" }}, valid_session
        assigns(:requirement_template).should eq(requirement_template)
      end

      it "re-renders the 'edit' template" do
        requirement_template = RequirementTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequirementTemplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => requirement_template.to_param, :requirement_template => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested requirement_template" do
      requirement_template = RequirementTemplate.create! valid_attributes
      expect {
        delete :destroy, {:id => requirement_template.to_param}, valid_session
      }.to change(RequirementTemplate, :count).by(-1)
    end

    it "redirects to the requirement_templates list" do
      requirement_template = RequirementTemplate.create! valid_attributes
      delete :destroy, {:id => requirement_template.to_param}, valid_session
      response.should redirect_to(requirement_templates_url)
    end
  end

end
